# Generated by Django 3.1.1 on 2021-01-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='usre',
            new_name='user',
        ),
    ]
