# Generated by Django 3.1.4 on 2021-01-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
